name: Update Documentation

on:
  push:
    branches-ignore:
      - "fix/**" # Игнорировать ветки, начинающиеся с fix/

jobs:
  update-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Generate Doxyfile if not present
        run: |
          if [ ! -f Doxyfile ]; then
            doxygen -g
          fi

      - name: Run Doxygen
        run: |
          doxygen Doxyfile

      - name: Checkout Wiki
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}.wiki.git
          token: ${{ secrets.GITHUB_TOKEN }}
          path: wiki

      - name: Update Wiki
        run: |
          cp -r docs/html/* wiki/
          cd wiki
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Update documentation"
          git push