# MegaLinter GitHub Action configuration file
# More info at https://megalinter.io
---
name: MegaLinter
on:
  push:
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  packages: read
  statuses: write
  pull-requests: write
  issues: write

env:
  APPLY_FIXES: all
  APPLY_FIXES_EVENT: pull_request
  APPLY_FIXES_MODE: pull_request

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: MegaLinter
        uses: oxsecurity/megalinter/flavors/python@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          # Отключаем некоторые проверки cpplint
          CPP_CPPLINT_ARGUMENTS: "--filter=-whitespace,-legal/copyright"
          C_CPPLINT_ARGUMENTS: "--filter=-whitespace,-legal/copyright"
          
          # Настройка Python линтеров
          PYTHON_BLACK_ARGUMENTS: "--line-length=100"
          PYTHON_FLAKE8_ARGUMENTS: "--max-line-length=100"
          
          # Игнорируем некритичные предупреждения
          MARKDOWN_MARKDOWNLINT_DISABLE_ERRORS: true
          REPOSITORY_CHECKOV_DISABLE_ERRORS: true
          REPOSITORY_KICS_DISABLE_ERRORS: true

      - name: Create Pull Request
        if: ${{ success() }} || ${{ failure() }}
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "[MegaLinter] Apply linter fixes"
          title: "chore: MegaLinter fixes"
          body: |
            Auto-generated PR with fixes from MegaLinter