# MegaLinter GitHub Action configuration file
# More info at https://megalinter.io
---
name: MegaLinter
on:
  push:
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  packages: read
  statuses: write
  pull-requests: write
  issues: write

env:
  APPLY_FIXES: all
  APPLY_FIXES_EVENT: pull_request
  APPLY_FIXES_MODE: pull_request

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: MegaLinter
        id: megalinter
        uses: oxsecurity/megalinter/flavors/python@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CPP_CPPLINT_ARGUMENTS: "--filter=-whitespace,-legal/copyright"
          C_CPPLINT_ARGUMENTS: "--filter=-whitespace,-legal/copyright"
          PYTHON_BLACK_ARGUMENTS: "--line-length=100"
          PYTHON_FLAKE8_ARGUMENTS: "--max-line-length=100"
          MARKDOWN_MARKDOWNLINT_DISABLE_ERRORS: true
          REPOSITORY_CHECKOV_DISABLE_ERRORS: true
          REPOSITORY_KICS_DISABLE_ERRORS: true
          SPELL_CSPELL_DISABLE: true
          DISABLE_LINTERS: cspell,git_diff,bandit,jscpd
          DISABLE: C
          SPELL_MISSPELL_DISABLE: true

      - name: Create Pull Request
        if: steps.megalinter.outcome == 'failure' || steps.megalinter.outcome == 'success'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "[MegaLinter] Apply linter fixes"
          title: "chore: MegaLinter fixes"
          body: |
            ## Автоматические исправления от MegaLinter
            
            Этот PR содержит исправления, предложенные MegaLinter.
            Пожалуйста, проверьте изменения перед слиянием.
            
            Статус проверки: ${{ steps.megalinter.outcome }}