name: myFirstDevOpsExperienceOnPush

on:
  pull_request:

env:
  MEGALINTER_CONFIG_FILE: .github/.mega-linter.yml
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  APPLY_FIXES: all
  APPLY_FIXES_EVENT: pull_request
  APPLY_FIXES_MODE: commit

jobs:
  linter:
    name: Run MegaLinter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Run MegaLinter
        uses: oxsecurity/megalinter@v8
        env:
          APPLY_FIXES: all
          APPLY_FIXES_MODE: commit
          VALIDATE_ALL_CODEBASE: true
          DISABLE_ERRORS: true
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Comment PR
        if: github.event_name == 'pull_request' && always() && (steps.megalinter.outcome != 'skipped')
        uses: actions/upload-artifact@v4
        with:
          name: Mega-Linter reports
          path: |
            megalinter-reports
            mega-linter.log
