name: runTests

on:
  pull_request: 
    branches:
      - master
      - main
jobs:
  name: LexerTestOnUbuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install cpp + cmake
        run: |
          sudo apt-get install -y cmake
          sudo apt-get install -y ninja
          sudo apt-get install -y g++
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -G Ninja ../backend
          ninja
      - name: Run tests
        run: |
          cd build
          ./backend 
          