name: myFirstDevOpsExperienceOnPush

on:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  APPLY_FIXES: all
  APPLY_FIXES_EVENT: pull_request
  APPLY_FIXES_MODE: commit

jobs:
  linter:
    name: Run MegaLinter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Run MegaLinter
        uses: oxsecurity/megalinter@v8
        env:
          APPLY_FIXES: all
          APPLY_FIXES_MODE: commit
          VALIDATE_ALL_CODEBASE: true
          DISABLE_ERRORS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Changes
        id: get-changes
        if: always() && (steps.megalinter.outcome != 'skipped')
        run: |
          changes=$(git diff --no-color)
          echo "changes<<EOF" >> $GITHUB_ENV
          echo "$changes" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Pull Request
        if: github.event_name == 'push'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          commit-message: "[MegaLinter] Apply linter fixes"
          title: "MegaLinter fixes"
          branch: "fix/AutoLinterFixes"
          base: ${{ github.head_ref }}
          body: |
            ## Автоматические исправления от MegaLinter

            Этот PR содержит исправления, предложенные MegaLinter.

  build-and-test:
    name: Build and Test on Ubuntu
    needs: linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build g++ python3 python3-pip

      - name: Build Project
        run: |
          mkdir -p build
          cd build
          cmake -G Ninja ../backend
          ninja

      - name: Run Tests
        run: |
          cd tests
          python3 tester.py
