name: runTests

on:
  pull_request: 
    branches:
      - master
      - main
  push:
jobs:
  TestOnUbuntu:
    needs: FormatCode
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install cpp + cmake
        run: |
          sudo apt-get install -y cmake
          sudo apt-get install -y ninja-build
          sudo apt-get install -y g++
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -G Ninja ../backend
          ninja
      - name: Setup Python
        run: | 
          sudo apt-get install -y python3
          sudo apt-get install -y python3-pip
          mv backend ../tests
          cd ../tests
      - name: Start Tests
        run: |
          cd tests
          ls
          python3 tester.py
  FormatCode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install clang-format
        run: |
          sudo apt-get install -y clang-format
      - name: Format
        run: |
          clang-format -i -style=.clang-format backend/*.cpp
          clang-format -i -style=.clang-format backend/*.h
          git diff --exit-code