name: runTests

on:
  push:
  pull_request:
    branches:
      - main
      - master

jobs:
  megalinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set APPLY_FIXES
        shell: bash
        run: |
          if [ "$GITHUB_EVENT_NAME" = "push" ]; then
            echo "APPLY_FIXES=all" >> $GITHUB_ENV
          else
            echo "APPLY_FIXES=none" >> $GITHUB_ENV
          fi

      - name: Run MegaLinter
        uses: oxsecurity/megalinter@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLY_FIXES: ${{ env.APPLY_FIXES }}
          COMMIT_MESSAGE: "chore: MegaLinter fixes"
          COMMIT_AUTHOR: "github-actions[bot]"
          COMMIT_EMAIL: "github-actions[bot]@users.noreply.github.com"

  TestOnUbuntu:
    needs: [megalinter]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install cpp + cmake
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build g++

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -G Ninja ../backend
          ninja
      - name: Setup Python
        run: | 
          sudo apt-get install -y python3 python3-pip
          mv backend ../tests
          cd ../tests

      - name: Start Tests
        run: |
          cd tests
          ls
          python3 tester.py