name: runTests

on:
  pull_request: 
    branches:
      - master
      - main
  push:
jobs:
  TestOnUbuntu:
    needs: FormatCode
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install cpp + cmake
        run: |
          sudo apt-get install -y cmake
          sudo apt-get install -y ninja-build
          sudo apt-get install -y g++
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -G Ninja ../backend
          ninja
      - name: Setup Python
        run: | 
          sudo apt-get install -y python3
          sudo apt-get install -y python3-pip
          mv backend ../tests
          cd ../tests
      - name: Start Tests
        run: |
          cd tests
          ls
          python3 tester.py
  FormatCode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install clang-format
        run: |
          sudo apt-get install -y clang-format
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'
          tidy-checks: ''
      - name: PushOnGit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-username"
          git add .
          git commit -m "Automated code formatting"
          git push